services:
  admin:
    image: kevinad/dreamsite-admin:develop
    restart: always
    env_file: .env.local
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: 'false'
      # Configuration de sécurité Strapi
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
    volumes:
      - ./back:/app  # Montez le répertoire du projet pour le développement en direct
      - ./back/config:/app/config  # Conserve la config Strapi
      - ./back/public/uploads:/app/public/uploads  # Conserve les fichiers uploadés
      - ./back/src/plugins:/app/src/plugins  # Conserve les plugins installés
      - /app/node_modules  # Empêche les conflits avec node_modules dans l’image
    ports:
      - '1337:1337'
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql  # Stockage persistant pour MySQL
    ports:
      - '3306:3306'

volumes:
  db_data:
